### ISSUE TITLE
项目缺少XML文件

### ISSUE THREAD

**Issue by loukai99** [eyounx/POSEC#1]
在`change_env_config.py`中的语句`tree = read_xml("/home/zhangc/gym/gym/envs/mujoco/assets/pusher.xml")`使用的文件`pusher.xml`是不是没有包含在本项目中啊，请问该模型应该如何构建，作者在对应的论文中所描述的内容不足够构建这个模型阿

**Comment by eyounx** [comment]
You may need to change the path of the pusher environment, which is included in the OpenAI Gym environments and can be downloaded from OpenAI website.
